general:
  data_base_dir: /app/data
  version: 1.0
  description: default configuration for Bamf NNUnet MR Prostate segmentation (dicom to dicom)

execute:
- DicomImporter
- NiftiConverter
- NNUnetRunner
- DsegConverter
- DataOrganizer

modules:
  DicomImporter:
    source_dir: input_data
    import_dir: sorted_data
    sort_data: true
    meta: 
      mod: 'mr'

  NNUnetRunner:
    in_data: 'nifty:mod=mr'
    nnunet_task: 'Task788_ProstateX'
    nnunet_model: '3d_fullres'
    folds: '5'

  DsegConverter:
    source_segs: 'nifti:mod=seg'
    target_dicom: 'dicom:mod=mr'
    model_name: 'Bamf NNUnet MR Prostate'
    skip_empty_slices: True
    json_config_path: '/app/models/bamf_nnunet_mr_prostate/config/meta.json'

  DataOrganizer:
    targets:
    - dicomseg-->[i:sid]/bamf_nnunet_mr_prostate.seg.dcm