general:
  data_base_dir: /app/data
  version: 1.0
  description: default configuration for Bamf NNUnet Liver segmentation (dicom to dicom)

execute:
- DicomImporter
- NiftiConverter
- NNUnetRunner
- DsegConverter
- DataOrganizer

modules:
  DicomImporter:
    source_dir: input_data
    import_dir: sorted_data
    sort_data: true
    meta: 
      mod: '%Modality'

  NNUnetRunner:
    nnunet_task: 'Task773_Liver'
    nnunet_model: '3d_fullres'
    roi: LIVER,LIVER+NEOPLASM_MALIGNANT_PRIMARY
    
  DsegConverter:
    source_segs: ['nifti:mod=seg']
    model_name: 'NNUnet Liver'
    skip_empty_slices: True

  DataOrganizer:
    targets:
    - dicomseg-->[i:sid]/nnunet_liver.seg.dcm