general:
  data_base_dir: /app/data
  version: 1.0
  description: Prostate MRI classification default (dicom to json)

execute:
- FileStructureImporter
- MhaConverter
- PicaiBaselineRunner
- ReportExporter
- DataOrganizer

modules:
  FileStructureImporter:
    input_dir: input_data
    structures:
      - $sid@instance/images/transverse-adc-prostate-mri@dicom:mod=mradc
      - $sid/images/transverse-t2-prostate-mri@dicom:mod=mrt2
      - $sid/images/transverse-hbv-prostate-mri@dicom:mod=mrhbv
    import_id: sid

  MhaConverter:
    engine: panimg

  ReportExporter:
    format: compact
    includes:
      - data: prostate_cancer_probability
        label: prostate_cancer_probability
        value: value

  DataOrganizer:
    targets:
      - json:mod=report-->[i:sid]/cspca-case-level-likelihood.json
      - mha:mod=hm-->[i:sid]/cspca-detection-map.mha
