general:
  data_base_dir: /app/data
  version: 1.0
  description: "FMCIB pipeline"

execute:
- FileStructureImporter
- FMCIBRunner
- DataOrganizer

modules:
  FileStructureImporter:
    structures:
      - $patientID/CT.nrrd@instance@nrrd:mod=ct
      - $patientID/masks/GTV-1.nrrd@nrrd
    import_id: patientID

  DataOrganizer:
    targets:
      - json-->[i:patientID]/features.json