general:
  data_base_dir: /app/data
  version: 1.0
  description: Lung-Lobe segmentation default (dicom to dicom)
  
execute:
- DicomImporter
- MhaConverter
- LobeSegmentationRunner
- DsegConverter
- DataOrganizer

modules:
  DicomImporter:
    source_dir: input_data
    import_dir: sorted_data
    sort_data: True
    meta: 
      mod: ct

  DsegConverter:
    source_segs: [mha:mod=seg:roi=*]
    dicomseg_json_path: /app/models/xie2020_lobe_segmentation/config/dseg.json
    skip_empty_slices: True

  DataOrganizer:
    targets:
      - dicomseg:mod=seg-->[i:sid]/gc_lunglobes.seg.dcm