general:
  data_base_dir: /app/data
modules:

  DicomImporter:
    source_dir: input_data
    import_dir: sorted_data
    sort_data: true
    meta: 
      mod: ct

  NNUnetRunner:
    folds: all
    task: Task400_OPEN_HEART_1FOLD
    model: 3d_lowres

  CasustRunner:
    test_time_augmentation: 0
    
  DsegConverter:
    dicomseg_json_path: /app/models/casust/config/dseg.json
    skip_empty_slices: True
