general:
  data_base_dir: /app/data
modules:

  DicomImporter:
    source_dir: input_data
    import_dir: sorted_data
    sort_data: true
    meta: 
      mod: ct

  NNUnetRunner:
    nnunet_task: 'Task003_Liver'
    nnunet_model: '3d_lowres'
    
  DsegConverter:
    source_segs: ['nifti:mod=seg']
    json_config_path: /app/models/nnunet_liver/config/meta.json
    model_name: 'NNUnet Pancreas'
    skip_empty_slices: True
