general:
  data_base_dir: /app/data

modules:

  DicomImporter:
    source_dir: input_data
    import_dir: sorted_data
    sort_data: true
    meta: 
      mod: ct

  TotalSegmentatorRunner:
    use_fast_mode: true

  DsegConverter:
    model_name: TotalSegmentator
    json_config_path: /app/models/totalsegmentator/config/dicomseg_metadata_whole.json
    skip_empty_slices: True
  
