general:
  version: 1.0
  data_base_dir: /app/data
  description: base configuration for GC NNUnet Pancreas model (dicom to dicom)

execute:
- DicomImporter
- MhaConverter
- GCNNUnetPancreasRunner
- DsegConverter
- DataOrganizer

modules:
  DicomImporter:
    source_dir: input_data
    import_dir: sorted_data
    sort_data: true
    meta: 
      mod: ct

  MhaConverter:
    engine: panimg

  DsegConverter:
    model_name: 'GC NNUnet Pancreas'
    source_segs: ['mha:mod=seg']
    target_dicom: dicom:mod=ct
    skip_empty_slices: True
    json_config_path: /app/models/gc_nnunet_pancreas/config/dseg.json

  DataOrganizer:
    targets:
    - mha:mod=heatmap-->[i:sid]/nnunet_pancreas_heatmap.mha
    - mha:mod=seg-->[i:sid]/nnunet_pancreas.seg.mha
    - dicomseg:mod=seg-->[i:sid]/nnunet_pancreas.seg.dcm
