general:
  data_base_dir: /app/data
  version: 1.0.0
  description: run platipy pipeline in MRunner (3D Slicer extension)

execute:
- NrrdImporter
- NiftiConverter
- PlatipyRunner
- JsonSegExporter
- DataOrganizer

modules:
  NrrdImporter:
    input_dir: input_data
    input_file_name: image.nrrd

  JsonSegExporter:
    targets:
    - nifti:mod=seg-->[d:roi].nii.gz
    
  DataOrganizer:
    targets:
    - nifti:mod=seg-->[d:roi].nii.gz
    - json-->segdef.json
