name: Pull Request Checks

on:
  pull_request:
    branches:
      - main  # Adjust to your repository's main branch

jobs:
  check:
    runs-on: ubuntu-latest

    env:
      SCRIPTS_DIR: ./.github/scripts
      SCHEMAS_DIR: ./.github/schemas

    steps:
    
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Get List of Changed Files
        id: changed_files
        run: |
          # Get a list of changed files in the PR
          CHANGED_FILES=$(git diff --name-only ${{ github.base_ref }}...${{ github.head_ref }})

          # Extract the directories from the file paths
          CHANGED_FOLDERS=$(echo "$CHANGED_FILES" | xargs -I % dirname % | sort -u)

          # Store the list of changed folders as an output variable
          echo "::set-output name=changed_folders::$CHANGED_FOLDERS"
        
      - name: Print Changed Folders
        run: |
          # Access the list of changed folders from the previous step's output
          echo "Changed Folders: ${{ steps.changed_files.outputs.changed_folders }}"
